### ISSUE TITLE
Error when applying timeout to WBEMConnection in python 2.7

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#287] opened 2016-05-05 21:44 UTC
call was WBEMCLI .... -t 5
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1080, in run
    self.finished.wait(self.interval)
  File "/usr/lib/python2.7/threading.py", line 620, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 348, in wait
    endtime = _time() + timeout
TypeError: unsupported operand type(s) for +: 'float' and 'str'

Same issue in python 3

Note that this only occurs because I found another error in pr 279 (was not putting the timeout
into the wbemconnection and fixed it.

**Comment by andy-maier** [comment] 2016-05-06 06:52
The root cause is that wbemcli (in the current version in PR #279) passes `opts.timeout` to `WBEMConnection` without first transforming it to a number.

The `WBEMConnection` description for its `timeout` parameter states it must be a number (int, long, float). The `opts.timeout` value is a string.

Will supply a PR for this, on top of the branch of PR #279.

**Comment by KSchopmeyer** [comment] 2016-05-06 14:45
The only discussion item would be if the typeerror message is really helpful or confusing.

The code that found this in wbemcli has been fixed as part of pr#279

**Comment by KSchopmeyer** [comment] 2016-05-06 15:17
Marked fixed with the last change to pr#279

**Comment by KSchopmeyer** [comment] 2016-05-06 16:20
moved this back to 8.4

**Comment by andy-maier** [comment] 2016-05-10 01:46
This has been fixed in 0.9 (which is correct, we should not roll this back into 0.8). CHanging milestone to reflect that, and closing the issue.

**Closed by andy-maier** 2016-05-10 01:46 UTC
Labels: area: code, resolution: fixed
