### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.26.8) or chardet (4.0.0) doesn't match a supported version!

### ISSUE THREAD

**Issue by rchateauneu** [pywbem/pywbem#2854] opened 2022-02-12 14:52 UTC
I try to run this pywbem command on a freshly installed wmimapper service. This command hangs (cannot stop it with Ctrl-C):

`C:\Users\rchat>python -c "import pywbem;c=pywbem.WBEMConnection('http://127.0.0.1:5988',None);c.ExecQuery('WQL','','root/cimv2')"
C:\Users\rchat\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
`

Maybe wmimapper is not properly configured, but maybe this warning is an interesting hint.

**Comment by andy-maier** [comment] 2022-03-10 17:39
Remy, can you please post the "pip list" output from the Python environment where this error occurs?

**Comment by andy-maier** [comment] 2022-03-10 17:51
The "requests" package issues this warning, if the following package version requirements are not satisfied:

```
    urllib3 >= 1.21.1, <= 1.26
    chardet >= 3.0.2, < 5.0.0
    charset_normalizer >= 2.0.0 < 3.0.0
```
One of chardet or charset_normalizer must be intalled.
The conditions above are from requests 2.27.1.

The package requirements for these two packages in that "requests" version are consistent with that:
```
    'chardet>=3.0.2,<5; python_version < "3"',
    'charset_normalizer~=2.0.0; python_version >= "3"',
    'urllib3>=1.21.1,<1.27',
```

**Comment by andy-maier** [comment] 2022-03-29 15:24
@rchateauneu Any update on this?

**Comment by rchateauneu** [comment] 2022-03-29 16:04
No visible conflicts when installing it.

**Comment by andy-maier** [comment] 2022-03-30 06:35
Ok, then my conclusion is that the dependencies of pywbem do not need to be changed, but there was something in your installation that changed the installed packages, causing the check in the requests package to go off.

I do not think that the "hang" you are seeing is related to the package version warning.

I was trying to reproduce the behavior with Karl's OpenPegasus container (keyporttech/smi-server:0.1.2) that was started and then paused, and with an EnumerateInstances() on CIM_ManagedElement that normally returns 54 instances within a few seconds on first use, and within sub-second afterwards.

Your code shown above does not specify the `timeout` parameter of `WBEMConnection`. The default value is `None`, and the pywbem documentation says:

"A value of None means that the connection uses the standard timeout behavior of Python sockets, which can be between several minutes and much longer. Because this is somewhat unpredictable, it is recommended to specify a value for the timeout."

Also, because of 2 retries, the time until pywbem times out is 3 times the specified timeout value. This is not described in the current docs, and we have issue #2853 open to clarify that in the docs.

When I specified `timeout=30` with the paused OpenPegasus container, pywbem raised `ConnectionError` after 1m30.7s. When I did not specify `timeout`, pywbem did not raise the exception within 15 minutes, after which I Ctrl-C'ed pywbem.

So my suspicion is that wmimapper allows the connection of pywbem, but then does not respond for a long time (or not at all). If you specify the `timeout` parameter, you should see pywbem raising `ConnectionError` after 3 times the specified timeout value.

**Comment by andy-maier** [comment] 2022-03-30 06:40
Sorry we could not provide a solution and could just point to wmimapper.
I am closing this issue - if you have new news, feel free to reopen this one or a new one.

**Closed by andy-maier** 2022-03-30 06:40 UTC
Labels: question, resolution: no issue
