### ISSUE TITLE
Add ability to capture time information from the server

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#672] opened 2017-02-24 14:04 UTC
The DMTF Specifications provide for a WBEM server to provide detailed timing information to the client.  See the DTMF cim/xml specifications for details.

We propose to add this to pywbem as an option.

**Comment by KSchopmeyer** [comment] 2017-03-17 14:28
See pr # 761

**Comment by andy-maier** [comment] 2017-04-24 09:04
This is a duplicate of issue #687, which is more detailed than this one. Closing this one as a duplicate.

**Closed** 2017-04-24 09:04 UTC
Labels: area: code, release: mandatory, resolution: duplicate
