### ISSUE TITLE
Efficiency  / Handling the copying of the XML prefix string to data on http output

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#418] opened 2016-07-05 15:11 UTC
In all cases we add the <-xml ...> string to http data by prefixing it as follows:

cim_http.py
``` 
    data = b'<?xml version="1.0" encoding="utf-8" ?>\n' + data
``` 

_listener.py (two places)
``` 
        resp_body = b'<?xml version="1.0" encoding="utf-8" ?>\n' + resp_xml.toxml()
``` 

While it works, there are questions about concatenating binary data to other data including the output form (is it unicode), is this efficient, etc.

**Comment by KSchopmeyer** [comment] 2016-07-05 16:20
This is a real issue.  In pywbem 3 just hit it with

  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_listener.py", line 441, in send_success_response
    resp_xml.toxml()
TypeError: can't concat bytes to str

**Comment by andy-maier** [comment] 2016-07-06 13:17
If the solution is to use the `toxml()` capability to encode to byte string, then let's double check whether we also have that ability when we move from minidom to lxml.

**Comment by andy-maier** [comment] 2016-07-06 13:22
Update: The real issue with Python 3 described two comments up, had already been fixed in PR #409.

**Comment by andy-maier** [comment] 2016-07-06 13:23
The remaining issue is efficiency with the extra copy caused by prepending the header line, and probably of using minidom in general.

**Comment by andy-maier** [comment] 2017-12-17 12:50
If we exclude replacing minidom from this issue, then efficiency is the remaining issue. The handling of the XML prefix string is just one part of efficiency, the other (bigger) part is conversions between unicode strings and byte strings.

This issue can only reasonably be followed up if we use profiling. py.test has a profiling module (pytest-profiling) that could be used for that.

**Comment by andy-maier** [comment] 2018-04-12 18:24
IMO, copying a string on a request cannot be an efficiency issue. We are probably copying a ton of strings when building the CIM-XML, and this is just one more. Remember, this is the request, which is not very large.

**Discussion point:** I suggest closing this issue as won't fix without spending the time for measuring this exactly.

**Comment by KSchopmeyer** [comment] 2018-06-22 13:43
I agree with you.

Lets close this one.   Would be interesting, however, to run a profile test and use that to drive any efficiency changes.

**Closed** 2018-07-18 14:32 UTC
Labels: area: code, release: optional, resolution: wont fix, type: enhancement
