### ISSUE TITLE
MOF compiler and MOFWBEMConnection instance paths

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#853] opened 2017-11-30 17:18 UTC
Normally the mofcompiler and MOFWBEMConnection produce classes, instances, etc. into a repository
for tests, etc.

I was having problem using the instances because the path component is only created in certain circumstances.  Turns out that the compiler only creates the path component of an instance when
the instance definition include the alias component (as $<blah>) otherwise it puts the instances into the local repository without a path component.  I am not sure if that is logical or not.

The instance created include the correct path at least if the Alias mechanism is used.  Thus,

        class TST_Person{
                [Key, Description ("This is key prop")]
            string name;
            string extraProperty = "defaultvalue";
        };
        [Association, Description(" Lineage defines the  relationship between parents and children.") ]
        class TST_Lineage
        {
            [key] TST_Person ref parent;
            [key] TST_Person ref child;
        };

and the instance definitions:

        instance of TST_Person as $Mike { name = "Mike"; };
        instance of TST_Person as $Sofi { name = "Sofi"; };
        instance of TST_Lineage
        {
            parent = $Mike;
            child = $Sofi;
        };

produces instances as follows:

    instances: namespace: root/blah

    path=root/blah:TST_Person.name="Mike"
    instance of TST_Person {
        name = "Mike";
    };

    path=root/blah:TST_Person.name="Sofi"
    instance of TST_Person {
        name = "Sofi";
    };

    path=root/blah:TST_Lineage
    instance of TST_Lineage {
        parent = root/blah:TST_Person.name="Mike";
        child = root/blah:TST_Person.name="Sofi";
    };

However, note that the path is complete and correct for the instances of TST_Person but it includes only the classname for the instance of the TST_Lineage class.

This is NOT a problem of multiple key properties since another class

        class TST_PersonNames{
                [Key, Description ("This is first key prop")]
            string firstname;
                [Key, Description ("This is secondkey prop")]
            string lastname;
            string extraProperty = "defaultvalue";
        };
        instance of TST_PersonNames as $PerNames{ firstname = "Fred";
                                                  lastname = 'Futz"; };

Also  creates the correct path:

    path=root/blah:TST_PersonNames.firstname="Fred",lastname="Futz"
    instance of TST_PersonNames {
        lastname = "Futz";
        firstname = "Fred";
    };

NOTE: the Pywbem classes in test.mof appears to avoid this issue because it uses CIM_Concreate collection which drops the use of reference properties as keys in favor of an InstanceID.

That did not work.  Here is result of the compile of that association. Again no path key bindings.

path=root/test:PyWBEM_MemberOfPersonCollection
instance of PyWBEM_MemberOfPersonCollection {
    Member = root/test:PyWBEM_Person.CreationClassName="PyWBEM_Person",Name="Bob";
    Collection = root/test:PyWBEM_PersonCollection.InstanceID="PersonCollection";
};

Once I added the alias definition to each instance it correctly creates the path for the association instances both in the case where the instanceID is a separate property and when the referenences are keys:

    path=root/cimv2:TST_Lineage.InstanceID="SaaraSofi"
    instance of TST_Lineage {
        InstanceID = "SaaraSofi";
        parent = root/cimv2:TST_Person.name="Saara";
        child = root/cimv2:TST_Person.name="Sofi";
    };
 
    path=root/cimv2:TST_Family.child="root/cimv2:TST_Person.name="Sofi"",parent="root/cimv2:
         TST_Person.name="Saara""
    instance of TST_Family {
        parent = root/cimv2:TST_Person.name="Saara";
        child = root/cimv2:TST_Person.name="Sofi";
    };

**Comment by andy-maier** [comment] 2017-12-01 14:44
Here is how I think it should work:

The MOF compiler should not calculate instance paths at all. It should issue a CreateInstance against its backend (=target) and that returns an instance path, which the MOF compiler should use. When there is an alias defined for an instance, that instance path is stored under the alias.
That gives us an instance path independent of whether there was an alias defined at the MOF level, and reduces the need for alias definitions atthe MOF level to what it is purposed for: Being a name that can be referenced when you need the instance path, like in the REF example you showed above.

**Comment by andy-maier** [comment] 2018-02-06 12:19
**Discussion point:** Discuss which direction we take with this issue.

**Comment by andy-maier** [comment] 2018-02-07 15:43
We agreed to close #937 as a duplicate of this issue here.

**Comment by andy-maier** [comment] 2018-02-07 15:53
We need to describe the limitations at the MOF level at least for the scenario of using the mof_compiler command against a WBEM server.

Known limitations are:
* In the MOF processed by the pywbem mof compiler, the alias must be defined before it is used. In DSP0004, that is not the case.
* In the MOF processed by the pywbem mof compiler, the key properties must be initialized (TBD: defaulting).
* A dynamic provide in the WBEM server that sets the key properties itself is not supported with the pywbem mof compiler.

**Comment by andy-maier** [comment] 2018-02-07 15:55
**Discussion point:** in 0.12, should we just document the limitations for MOF, or should we lift them?

**Comment by andy-maier** [comment] 2018-02-09 15:10
We agreed to the following on the items in my earlier comment, above:
- item 1: This is an issue that should be fixed.
- item 2: We want instances in MOF to be able to have an alias without a requirement for having one or more keys specified (or defaultred). Specifically, there is no requirement that multiple instances have different key values in MOF, as long as they have different aliases.

**Comment by andy-maier** [comment] 2018-02-09 15:16
We agreed to defer these two issues beyond v0.12.

**Comment by andy-maier** [comment] 2018-02-11 14:11
The issues have been reated (see comment above), so this issue can be closed.

**Comment by andy-maier** [comment] 2018-02-11 15:34
Reopened because we still need to document the current limitations.

**Comment by andy-maier** [comment] 2018-02-11 15:41
The limitations are documented in PR #1080. Along with the other issues that were opened, this addresses this issue here.

**Closed** 2018-02-11 17:47 UTC
Labels: area: code, release: optional, resolution: fixed, resolution: pursued in different issues, type: bug
