### ISSUE TITLE
Pywbemtools causes python-mock failure

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1816] opened 2019-08-27 01:27 UTC
Running the pywbemtools enumerate instances with the pywbem file simple_mock_model_ext.mof causes a failure with the message that an instance was duplicated in the repository.

We confirmed that apparently no instance was duplicated. 

We have traces in the corresponding pywbemtools issue https://github.com/pywbem/pywbemtools/issues/260

**Comment by andy-maier** [comment] 2019-09-19 05:39
Is this fixed by PR #1827?

**Comment by andy-maier** [comment] 2019-09-26 17:07
Karl will investigate and fix if needed.

**Comment by andy-maier** [comment] 2019-09-29 15:12
After discussing with Karl: This issue describes the symptom that is caused by issue #1852. Closing it as a duplicate.

**Closed** 2019-09-29 15:12 UTC
Labels: area: code, resolution: duplicate
