### ISSUE TITLE
Add tests for MOF_Compiler Cmd Line

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#730] opened 2017-07-21 12:55 UTC

**Comment by andy-maier** [comment] 2019-11-05 22:33
PR #1936 has decreased the test coverage of the `pywbem/_cliutils.py` module to 0%. The `tests/test_wbemutils.py` command that existed before that PR coul dbe used as a basis for creating a test program for the mof_compiler command.

**Comment by KSchopmeyer** [comment] 2020-03-27 15:54
Moved to 1.1.0.

**Comment by andy-maier** [comment] 2021-04-30 15:25
Closed as a duplicate of #428.

**Closed by andy-maier** 2021-04-30 15:25 UTC
Labels: area: test, type: enhancement
