### ISSUE TITLE
Client does not support the WBEMServerResponseTime header

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#276] opened 2016-05-02 07:05 UTC
DSP0200 1.4 defines the WBEMServerResponseTime HTTP header field that may be provided by a WBEM server in any response message. The PyWBEM Client does not support that in any way right now.

The function is simple for the client.  If the header WBEMServerResponseTime is part of the response it will contain a 64-bit unsigned integer value that represents the elapsed time in microseconds used by the server to process the request.

For our client that means adding one more field to statistics, WBEMServerResponseTime and, gathering this from the header if it exists and passing it to the statistics. The statistics would be extended to handle this like the current operation time (max/min/avg, etc.)

**Comment by andy-maier** [comment] 2016-05-06 07:27
After 0.9.0.

**Comment by KSchopmeyer** [comment] 2017-06-23 14:16
This is a duplicate of another issue

**Comment by KSchopmeyer** [comment] 2017-06-23 14:17
closing as duplicate

**Closed by KSchopmeyer** 2017-06-23 14:17 UTC
Labels: area: code, discussion needed, release: optional, type: standards compliance
