### ISSUE TITLE
mof_compiler adds file_line attribute to CIMError exceptions

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1235] opened 2018-04-24 21:57 UTC
The mof_compiler overloads the CIMError exception when it catches it by adding an extra attribute for line number and filename.

While this is not a major issue is is just one more thing that makes the compiler code hard to read and also an opening for an error if a new except CIMError is added and the developer forgets to add that extra line of code.

**Comment by andy-maier** [comment] 2019-11-09 05:03
The objected code stores the current file (from `parser.file`) and line (from `lexer.lineno`) at the time the issue is detected in a parser or token function, into an attribute `file_line` on the `CIMError` exception, e.g.:

        try:
            quals = p.parser.handle.EnumerateQualifiers()
        except CIMError as ce:
            if ce.status_code != CIM_ERR_INVALID_NAMESPACE:
                ce.file_line = (p.parser.file, p.lexer.lineno)
                raise

An attempt to replace this approach with getting file and line from `parser.file` and `lexer.lineno` directly at the time the `CIMError` exception is printed in `compile_string()` failed because at that time, the `lexer.lineno` value has already been reset to 1 for some reason. I verified this by comparing the lineno stored in the `CIMError` exception object with `lexer.lineno`, and that was always the case.

The only other possibility I see would be to raise a different exception than `CIMError`, that has file and lineno as official, documented attributes. That is a quite incompatible change.

**Discussion point:** Should we close this issue as won't fix?

**Comment by andy-maier** [comment] 2019-11-29 16:22
Karl and I agreed to go for option 1, since this is 1.0.0 and we believe that nobody actually programmed against the MOFCompiler class.

**Comment by andy-maier** [comment] 2019-12-03 09:11
Will be addressed in PR #1995.

**Closed** 2019-12-08 08:17 UTC
Labels: area: code, release: optional, resolution: fixed, type: cleanup
