### ISSUE TITLE
mof Compiler builds paths on instances only when alias defined

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#937] opened 2018-01-03 14:05 UTC
The mof compiler is inconsistent about when it puts paths on instances that it creates.  It adds the path when instance alias is defined but does not when there is no alias defined.

Thus: 

        class TST_Person{
                [Key, Description ("This is key prop")]
            string name;
            string extraProperty = "defaultvalue";
        };

Thus, the first instance definition below would set the path but the second would not:

        instance of TST_Person as $Mike { name = "Mike"; };
        instance of TST_Person{ name = "Saara"; };

**Discussion:**

1. Should the path be part of a created instance as output by the compiler?
2. Is this inconsistency logical or should we always put the path on or not put the path on.

**Comment by KSchopmeyer** [comment] 2018-01-03 16:00
Resolution: define the current behavior. The path exists only when you set the alias.

**Comment by KSchopmeyer** [comment] 2018-01-05 14:22
We agreed to not change this but to update the documentation to reflect that the compiler only puts paths on instances when there is an alias definition.

**Comment by andy-maier** [comment] 2018-02-07 15:42
We discussed this one and concluded it is a duplicate of issue #853.

**Closed by andy-maier** 2018-02-07 15:42 UTC
Labels: resolution: duplicate, area: docs, release: optional
