### ISSUE TITLE
Update pywbemlogger class for final release

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1093] opened 2018-02-20 16:08 UTC
We agreed with the release of 0.11.0 that the pywbemlogger class was an experimental means of configuring the pywbem logger. the goal of this was to define a convient means for users of pywbem to configure the specific loggers used by cim_operations to log request APIs and their responses and also the xml generated given that we wanted to  add one new piece of functionality not normally in loggers, the ability to define multiple output formats (detail or summary) for each logger.

We have found several issues with this implementation but cannot find anything better given that we are adding data to the logger configuration.

Specifically:

1. The documentation is oriented towards the implementation, not the user.

2. The documentation is incomplete and a number of characteristics such as defaults is not clarified.

3. It is not really a singleton in that it does not require the creation of a single object but uses the class level variables to store the configuration data

We did agree to keep the method that uses a string input to define the loggers as a common tool for clis that use pywbem.

**Comment by andy-maier** [comment] 2018-02-21 23:06
See also the last comment from today in the closed issue #859.

**Comment by andy-maier** [comment] 2018-04-04 08:58
**Discussion point:** Now that the reworked logging support has been merged (PR #1105), is there anything left in this regard? It seems to me we can just close this issue as a duplicate of #859.

**Comment by andy-maier** [comment] 2018-04-04 14:28
We agreed that this issue is superceded by issue #859 which is addressed. Closing as duplicate.

**Closed by andy-maier** 2018-04-04 14:28 UTC
Labels: area: code, discussion needed, release: optional, type: cleanup
