### ISSUE TITLE
How to build a WBEM server environment for IBM SVC?

### ISSUE THREAD

**Issue by tanshaolong** [pywbem/pywbem#1714] opened 2019-04-09 03:09 UTC
Hi everybody,

I have a IBM SVC V7000 device. I want to manage the storage by pywbem, but I don’t know how to build a WBEM server environment for IBM SVC. Who would tell me the steps? Or give some docs to refer? Thank you.

Best regards
Ray

**Comment by tanshaolong** [comment] 2019-04-09 09:25
According by my test, I think the WBEM server of IBM SVC is embedded in SVC controller. I have connected it, but I get exception when I run end2end tests. Who would give some hint for the error messages? Thank you.

The below is WBEM server definition.
servers:
  srv1:
    description: My WBEM server
    url: https://192.168.**.**:5989
    user: superuser
    password: ******
    no_verification: true
implementation_namespace: root/ibm

The below is the error message when run end2end test.
# make end2end
makefile: Running end2end tests
py.test --color=yes --pythonwarnings=default,ignore::DeprecationWarning,ignore::PendingDeprecationWarning -v --tb=short  tests/end2endtest -s
============================================================================ test session starts =============================================================================
platform linux2 -- Python 2.7.5, pytest-4.4.0, py-1.8.0, pluggy-0.9.0 -- /usr/bin/python2
cachedir: .pytest_cache
rootdir: /root/pywbem
plugins: cov-2.5.1
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/_pytest/main.py", line 209, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/_pytest/main.py", line 248, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/_pytest/warnings.py", line 150, in pytest_collection
INTERNALERROR>     config=config, ihook=config.hook, when="collect", item=None
INTERNALERROR>   File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
INTERNALERROR>     return self.gen.next()
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/_pytest/warnings.py", line 90, in catch_warnings_for_item
INTERNALERROR>     warnings._setoption(arg)
INTERNALERROR>   File "/usr/lib64/python2.7/warnings.py", line 120, in _setoption
INTERNALERROR>     action = _getaction(action)
INTERNALERROR>   File "/usr/lib64/python2.7/warnings.py", line 145, in _getaction
INTERNALERROR>     raise _OptionError("invalid action: %r" % (action,))
INTERNALERROR> _OptionError: invalid action: 'default,ignore'

======================================================================== no tests ran in 0.11 seconds ========================================================================
make: *** [end2end] Error 3

**Comment by andy-maier** [comment] 2019-04-10 15:13
I assume that your Pthon 2.7 version is too old, you are using 2.7.5, and apparently it does not support the options passed via the `--pythonwarnings` option.

What you can do to get over that issue is to remove that option, e.g. by changing the following in the `makefile` on line 279:

From:
```
    pytest_end2end_warnings_opts := --pythonwarnings=default,ignore::DeprecationWarning,ignore::PendingDeprecationWarning
```

To:
```
    pytest_end2end_warnings_opts :=
```

**Comment by andy-maier** [comment] 2019-04-10 15:13
Let us know whether that worked by posting here.

**Comment by tanshaolong** [comment] 2019-04-11 02:10
Yes, you are right. My python version is 2.7.5.  I made the changed that you mentioned at above. I didn't encounter this mistake again. Thanks you.

Also  I have 5 failed test cases and 2 warnings at my test enviroment. I don't know what cause the failed. Please see the detail test results.

================================================================================== FAILURES ==================================================================================
______________________________________________________________ test_undefined_profiles[server_definition=srv1] _______________________________________________________________
tests/end2endtest/test_profile_generic.py:107: in test_undefined_profiles
    undefined_profile_lines))
E   AssertionError: Server srv1 at https://192.168.0.8:5989 advertises the following profiles that are not defined in profiles.yml. This may be caused by incorrectly implemented profile names:
E   SNIA u'Cascading' 1.4.0
E   SNIA u'Masking and Mapping' 1.4.0
___________________________________________ Test_SNIA_Server_Profile.test_Namespace[assert_association_a1-server_definition=srv1] ____________________________________________
tests/end2endtest/test_profile_snia_server.py:104: in test_Namespace
    far_class='CIM_Namespace')
tests/end2endtest/utils/assertions.py:406: in assert_association_a1
    far_class, far_role)
tests/end2endtest/utils/assertions.py:835: in _assert_association_consistency
    assert_instance_of(conn, assoc_insts, assoc_class)
tests/end2endtest/utils/assertions.py:104: in assert_instance_of
    path.to_wbem_uri(), classname))
E   AttributeError: 'CIMInstance' object has no attribute 'to_wbem_uri'
___________________________________________ Test_SNIA_Server_Profile.test_Namespace[assert_association_a2-server_definition=srv1] ____________________________________________
tests/end2endtest/test_profile_snia_server.py:104: in test_Namespace
    far_class='CIM_Namespace')
tests/end2endtest/utils/assertions.py:479: in assert_association_a2
    far_class, far_role)
tests/end2endtest/utils/assertions.py:835: in _assert_association_consistency
    assert_instance_of(conn, assoc_insts, assoc_class)
tests/end2endtest/utils/assertions.py:104: in assert_instance_of
    path.to_wbem_uri(), classname))
E   AttributeError: 'CIMInstance' object has no attribute 'to_wbem_uri'
___________________________________________ Test_SNIA_Server_Profile.test_Namespace[assert_association_a3-server_definition=srv1] ____________________________________________
tests/end2endtest/test_profile_snia_server.py:104: in test_Namespace
    far_class='CIM_Namespace')
tests/end2endtest/utils/assertions.py:528: in assert_association_a3
    _inst = conn.GetInstance(path, asserted=True)
tests/end2endtest/utils/utils.py:276: in GetInstance
    return self._call_func('GetInstance', *args, **kwargs)
tests/end2endtest/utils/utils.py:251: in _call_func
    self.raise_as_assertion_error(exc, funcname, *args, **kwargs)
tests/end2endtest/utils/utils.py:264: in raise_as_assertion_error
    exc.__class__.__name__, exc, parm_str))
E   AssertionError: Server srv1 at https://192.168.0.8:5989: WBEMConnection.GetInstance() failed and raised CIMError - 6 (CIM_ERR_NOT_FOUND): CIM_ERR_NOT_FOUND: IBMTSSVC_NamespaceInManagerInterop.Antecedent="interop:IBMTSSVC_ObjectManagerInterop.CreationClassName=\"IBMTSSVC_ObjectManagerInterop\",Name=\"IBMTSSVC:192.168.0.8\",SystemCreationClassName=\"IBMTSSVC:ObjectManagerInterop\",SystemName=\"IBM SVC CIMOM\"",Dependent="interop:IBMTSSVC_NameSpaceInterop.CreationClassName=\"IBMTSSVC_NameSpaceInterop\",Name=\"interop\",ObjectManagerCreationClassName=\"IBMTSSVC_ObjectManagerInterop\",ObjectManagerName=\"IBMTSSVC:192.168.0.8\",SystemCreationClassName=\"IBMTSSVC:NameSpaceInterop\",SystemName=\"IBM NamespaceInterop\"". Parameters: (CIMInstanceName(classname='IBMTSSVC_NamespaceInManagerInterop', keybindings=NocaseDict({'Dependent': CIMInstanceName(classname='IBMTSSVC_NameSpaceInterop', keybindings=NocaseDict({'ObjectManagerCreationClassName': 'IBMTSSVC_ObjectManagerInterop', 'SystemName': 'IBM NamespaceInterop', 'Name': 'interop', 'CreationClassName': 'IBMTSSVC_NameSpaceInterop', 'ObjectManagerName': 'IBMTSSVC:192.168.0.8', 'SystemCreationClassName': 'IBMTSSVC:NameSpaceInterop'}), namespace='interop', host=None), 'Antecedent': CIMInstanceName(classname='IBMTSSVC_ObjectManagerInterop', keybindings=NocaseDict({'CreationClassName': 'IBMTSSVC_ObjectManagerInterop', 'SystemName': 'IBM SVC CIMOM', 'Name': 'IBMTSSVC:192.168.0.8', 'SystemCreationClassName': 'IBMTSSVC:ObjectManagerInterop'}), namespace='interop', host=None)}), namespace='root/ibm', host='newinstall'))
___________________________________________ Test_SNIA_Server_Profile.test_Namespace[assert_association_a4-server_definition=srv1] ____________________________________________
tests/end2endtest/test_profile_snia_server.py:104: in test_Namespace
    far_class='CIM_Namespace')
tests/end2endtest/utils/assertions.py:607: in assert_association_a4
    _inst = conn.GetInstance(path, asserted=True)
tests/end2endtest/utils/utils.py:276: in GetInstance
    return self._call_func('GetInstance', *args, **kwargs)
tests/end2endtest/utils/utils.py:251: in _call_func
    self.raise_as_assertion_error(exc, funcname, *args, **kwargs)
tests/end2endtest/utils/utils.py:264: in raise_as_assertion_error
    exc.__class__.__name__, exc, parm_str))
E   AssertionError: Server srv1 at https://192.168.0.8:5989: WBEMConnection.GetInstance() failed and raised CIMError - 6 (CIM_ERR_NOT_FOUND): CIM_ERR_NOT_FOUND: IBMTSSVC_NamespaceInManagerInterop.Antecedent="interop:IBMTSSVC_ObjectManagerInterop.CreationClassName=\"IBMTSSVC_ObjectManagerInterop\",Name=\"IBMTSSVC:192.168.0.8\",SystemCreationClassName=\"IBMTSSVC:ObjectManagerInterop\",SystemName=\"IBM SVC CIMOM\"",Dependent="interop:IBMTSSVC_NameSpaceInterop.CreationClassName=\"IBMTSSVC_NameSpaceInterop\",Name=\"interop\",ObjectManagerCreationClassName=\"IBMTSSVC_ObjectManagerInterop\",ObjectManagerName=\"IBMTSSVC:192.168.0.8\",SystemCreationClassName=\"IBMTSSVC:NameSpaceInterop\",SystemName=\"IBM NamespaceInterop\"". Parameters: (CIMInstanceName(classname='IBMTSSVC_NamespaceInManagerInterop', keybindings=NocaseDict({'Dependent': CIMInstanceName(classname='IBMTSSVC_NameSpaceInterop', keybindings=NocaseDict({'ObjectManagerCreationClassName': 'IBMTSSVC_ObjectManagerInterop', 'SystemName': 'IBM NamespaceInterop', 'Name': 'interop', 'CreationClassName': 'IBMTSSVC_NameSpaceInterop', 'ObjectManagerName': 'IBMTSSVC:192.168.0.8', 'SystemCreationClassName': 'IBMTSSVC:NameSpaceInterop'}), namespace='interop', host=None), 'Antecedent': CIMInstanceName(classname='IBMTSSVC_ObjectManagerInterop', keybindings=NocaseDict({'CreationClassName': 'IBMTSSVC_ObjectManagerInterop', 'SystemName': 'IBM SVC CIMOM', 'Name': 'IBMTSSVC:192.168.0.8', 'SystemCreationClassName': 'IBMTSSVC:ObjectManagerInterop'}), namespace='interop', host=None)}), namespace='root/ibm', host='newinstall'))
============================================================================== warnings summary ==============================================================================
tests/end2endtest/utils/pytest_extensions.py:34
  /root/pywbem/tests/end2endtest/utils/pytest_extensions.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    PROFILE_DEFINITION_LIST = yaml.load(_fp)

tests/end2endtest/test_profile_snia_server.py::Test_SNIA_Server_Profile::test_ObjectManagerCommunicationMechanism[assert_association_a1-server_definition=srv1]
  /root/pywbem/tests/end2endtest/test_profile_snia_server.py:196: ToleratedServerIssueWarning: Downgraded the following test failure to a warning: AssertionError: Server srv1 at https://192.168.0.8:5989: Property value issue: The value of array property 'FunctionalProfilesSupported' in an instance of class 'IBMTSSVC_CIMXMLCommunicationMechanismInterop' does not contain value 0, but is [2, 3, 5, 6, 7, 8, 9]
    ToleratedServerIssueWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================================================== 5 failed, 66 passed, 61 skipped, 2 warnings in 89.40 seconds ========================================================
make: *** [end2end] Error 1

**Comment by andy-maier** [comment] 2019-04-11 11:15
Glad to hear you got further, and thanks for reporting the issues you found!

Here are some initial comments:

1. On this AssertionError:
   ```
   E AssertionError: Server srv1 at https://192.168.0.8:5989 advertises the following profiles that are not defined in profiles.yml. This may be caused by incorrectly implemented profile names:
   E SNIA u'Cascading' 1.4.0
   E SNIA u'Masking and Mapping' 1.4.0
   ```
   * The "Cascading" profile was missing in the pywbem profile definitions in `tests/profiles/profiles.yml` and has been added in PR #1716. Reason it was not defined so far was that it is not described in the SMI-S specs. Started dialog with Mike Walker to clarify that.
   * The pywbem profile definitions had the name of the "Masking and Mapping" profile as "Masking And Mapping", and profile name matching is case sensitive. This has been fixed also in PR #1716.

**Comment by andy-maier** [comment] 2019-04-11 16:01
2. On the AttributeError: 'CIMInstance' object has no attribute 'to_wbem_uri' in test_Namespace():
   * This was caused by an error in the test code and is being fixed in PR #1717.

**Comment by andy-maier** [comment] 2019-04-11 16:04
3. On the two CIM_ERR_NOT_FOUND failures on GetInstance for the IBMTSSVC_NamespaceInManagerInterop association instances:
  * This is something we need to discuss in the group, as to whether we would consider that an implementation failure on the V7000, vs. tolerate it in the test code. We will need to consult with our SMI-S expert on that one.

**Comment by andy-maier** [comment] 2019-04-11 16:05
Again, this test was very fruitful. Thanks much!
It clearly showed that the end2end test capability has not yet had a lot of exposure. We'll work on that.

**Comment by tanshaolong** [comment] 2019-04-12 02:22
Thanks for your quick fix. :)

**Comment by andy-maier** [comment] 2019-04-12 17:03
The plan is to release a 0.14.2 version with all of these fixes in, sometimes next week.

**Comment by andy-maier** [comment] 2019-05-08 03:38
0.14.2 has been released and contains the fix for this issue.

**Closed by andy-maier** 2019-05-08 03:38 UTC
Labels: area: test, resolution: fixed, type: bug
