### ISSUE TITLE
AttributeError("'module' object has no attribute 'SSLContext'",) with Python 2.7

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1303] opened 2018-06-29 15:53 UTC
Starting this morning I am getting the following error when running make test with python 2.7.14

I have not investigated other than to remove and recreate the virtual enviroment to be sure it is not something messed up in that environment. Same issue with recreated virtual environment.

This works fine with python 3

This was on the branch ks/#1298-null-keybindings and I went ahead and pushed to code and it workin in Travis.

``

==================================== ERRORS ====================================
______________________________ ERROR collecting  _______________________________
../../../.virtualenvs/pywbem27/local/lib/python2.7/site-packages/py/_path/common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
../../../.virtualenvs/pywbem27/local/lib/python2.7/site-packages/py/_path/common.py:429: in gen
    for p in self.gen(subdir):
../../../.virtualenvs/pywbem27/local/lib/python2.7/site-packages/py/_path/common.py:419: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
../../../.virtualenvs/pywbem27/local/lib/python2.7/site-packages/_pytest/main.py:511: in _recurse
    ihook = self.gethookproxy(path)
../../../.virtualenvs/pywbem27/local/lib/python2.7/site-packages/_pytest/main.py:413: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
../../../.virtualenvs/pywbem27/local/lib/python2.7/site-packages/_pytest/config/__init__.py:383: in _getconftestmodules
    mod = self._importconftest(conftestpath)
../../../.virtualenvs/pywbem27/local/lib/python2.7/site-packages/_pytest/config/__init__.py:412: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: AttributeError("'module' object has no attribute 'SSLContext'",)
E     File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 216, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
E       exec2(obj, globals, locals)
E     File "<string>", line 7, in exec2
E     File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/testsuite/testclient/conftest.py", line 137, in <module>
E       import httpretty
E     File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/httpretty/__init__.py", line 28, in <module>
E       from . import core
E     File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/httpretty/core.py", line 102, in <module>
E       old_sslcontext_wrap_socket = ssl.SSLContext.wrap_socket

**Comment by KSchopmeyer** [comment] 2018-06-29 15:56
dings)$ pip list
Package                            Version      Location                                    
---------------------------------- ------------ --------------------------------------------
alabaster                          0.7.11       
astroid                            1.6.5        
atomicwrites                       1.1.5        
attrs                              18.1.0       
Babel                              2.6.0        
backports-abc                      0.5          
backports.functools-lru-cache      1.5          
backports.shutil-get-terminal-size 1.0.0        
backports.ssl-match-hostname       3.5.0.1      
bleach                             2.1.3        
certifi                            2018.4.16    
chardet                            3.0.4        
configparser                       3.5.0        
coverage                           4.0.3        
decorator                          4.3.0        
distro                             1.3.0        
docutils                           0.14         
entrypoints                        0.2.3        
enum34                             1.1.6        
flake8                             3.5.0        
funcsigs                           1.0.2        
functools32                        3.2.3.post2  
futures                            3.2.0        
gitdb2                             2.0.3        
GitPython                          2.1.10       
html5lib                           1.0.1        
httpretty                          0.9.5        
idna                               2.7          
imagesize                          1.0.0        
ipykernel                          4.8.2        
ipython                            5.7.0        
ipython-genutils                   0.2.0        
ipywidgets                         7.2.1        
isort                              4.3.4        
Jinja2                             2.10         
jsonschema                         2.6.0        
jupyter                            1.0.0        
jupyter-client                     5.2.3        
jupyter-console                    5.2.0        
jupyter-core                       4.4.0        
lazy-object-proxy                  1.3.1        
linecache2                         1.0.0        
lxml                               4.2.3        
M2Crypto                           0.30.1       
MarkupSafe                         1.0          
mccabe                             0.6.1        
mistune                            0.8.3        
mock                               2.0.0        
more-itertools                     4.2.0        
nbconvert                          5.3.1        
nbformat                           4.4.0        
notebook                           5.5.0        
packaging                          17.1         
pandocfilters                      1.4.2        
pathlib2                           2.3.2        
pbr                                4.0.4        
pexpect                            4.6.0        
pickleshare                        0.7.4        
pip                                10.0.1       
pkginfo                            1.4.2        
pluggy                             0.6.0        
ply                                3.11         
prompt-toolkit                     1.0.15       
ptyprocess                         0.6.0        
py                                 1.5.4        
pycodestyle                        2.3.1        
pyflakes                           1.6.0        
Pygments                           2.2.0        
pylint                             1.9.2        
pyparsing                          2.2.0        
pytest                             3.6.2        
pytest-cov                         2.5.1        
python-coveralls                   2.9.1        
python-dateutil                    2.7.3        
pytz                               2018.5       
pywbem                             0.12.1.dev55 /home/kschopmeyer/pywbem/githubpywbem/pywbem
PyYAML                             3.12         
pyzmq                              17.0.0       
qtconsole                          4.3.1        
requests                           2.19.1       
requests-toolbelt                  0.8.0        
scandir                            1.7          
Send2Trash                         1.5.0        
setuptools                         39.2.0       
simplegeneric                      0.8.1        
singledispatch                     3.4.0.3      
six                                1.11.0       
smmap2                             2.0.3        
snowballstemmer                    1.2.1        
Sphinx                             1.7.5        
sphinx-git                         10.1.1       
sphinxcontrib-websupport           1.1.0        
terminado                          0.8.1        
testfixtures                       5.4.0        
testpath                           0.3.1        
tornado                            4.5.3        
tqdm                               4.23.4       
traceback2                         1.4.0        
traitlets                          4.3.2        
twine                              1.11.0       
typing                             3.6.4        
unittest2                          1.1.0        
urllib3                            1.23         
wcwidth                            0.1.7        
webencodings                       0.5.1        
wheel                              0.31.1       
widgetsnbextension                 3.2.1        
wrapt                              1.10.11      
yamlordereddictloader              0.4.0

**Comment by andy-maier** [comment] 2018-06-30 14:04
I cannot reproduce this. I tried on CygWin with both an updated existing venv and with a fresh venv, both with CygWin's Python 2.7.14. The version of httpretty is also 0.9.5, and of M2Crypto is also 0.30.1.

Try removing your pip cache and see if that helps:
```
rm -rf $HOME/.cache/pip
make clobber install develop test
```

**Comment by andy-maier** [comment] 2018-09-05 15:10
Some more research on this issue:
* [this SO article](https://stackoverflow.com/questions/28228214) identified too old py27 version (2.7.6) as the reason.
* [this github issue](https://github.com/mjs/imapclient/issues/193) suggests installation of `libffi-dev` on Ubuntu solved it.
* [this boutysource article](https://www.bountysource.com/issues/59363842-ssl-sslcontext-wrap_socket-starting-with-0-9-5-under-python-2-7-8) points to httpretty 0.9.5 as the culprit.

Note that due to our support for Python 3.7, PR #1340 increased the version of httpretty to 0.9.5.

**Comment by andy-maier** [comment] 2018-09-28 14:35
Karl, if it occurred again on ubuntu 16, please post the details for that, including:

* exact distro version
* exact python version
* pip list output
* pywbem branch or version you used
* traceback that happened

Also, make sure you reproduce this:

* with a synchronized pywbem repo clone
* in a freshly created virtual Python environment
* by running `make all`

**Comment by andy-maier** [comment] 2018-09-28 15:00
I have tested this in a fresh Ubuntu 16.04 on AWS and could not reproduce it.

* Linux: Ubuntu 16.04 with latest `apt upgrade` as of today
* Python: 2.7.12
* Pywbem: master branch as of today (commit 6fdc956)
* Pip list of the virtualenv:

alabaster                          0.7.11        
astroid                            1.6.5         
atomicwrites                       1.2.1         
attrs                              18.2.0        
Babel                              2.6.0         
backports-abc                      0.5           
backports.functools-lru-cache      1.5           
backports.shutil-get-terminal-size 1.0.0         
bleach                             2.1.4         
certifi                            2018.8.24     
cffi                               1.11.5        
chardet                            3.0.4         
cmarkgfm                           0.4.2         
configparser                       3.5.0         
coverage                           4.0.3         
decorator                          4.3.0         
defusedxml                         0.5.0         
distro                             1.3.0         
docutils                           0.14          
entrypoints                        0.2.3         
enum34                             1.1.6         
flake8                             3.5.0         
funcsigs                           1.0.2         
functools32                        3.2.3.post2   
future                             0.16.0        
futures                            3.2.0         
gitdb2                             2.0.4         
GitPython                          2.1.11        
html5lib                           1.0.1         
httpretty                          0.9.5         
idna                               2.7           
imagesize                          1.1.0         
ipaddress                          1.0.22        
ipykernel                          4.10.0        
ipython                            5.8.0         
ipython-genutils                   0.2.0         
ipywidgets                         7.4.2         
isort                              4.3.4         
Jinja2                             2.10          
jsonschema                         2.6.0         
jupyter                            1.0.0         
jupyter-client                     5.2.3         
jupyter-console                    5.2.0         
jupyter-core                       4.4.0         
lazy-object-proxy                  1.3.1         
linecache2                         1.0.0         
lxml                               4.2.5         
M2Crypto                           0.30.1        
MarkupSafe                         1.0           
mccabe                             0.6.1         
mistune                            0.8.3         
mock                               2.0.0         
more-itertools                     4.3.0         
nbconvert                          5.4.0         
nbformat                           4.4.0         
notebook                           5.7.0         
packaging                          18.0          
pandocfilters                      1.4.2         
pathlib2                           2.3.2         
pbr                                4.2.0         
pexpect                            4.6.0         
pickleshare                        0.7.5         
pip                                18.0          
pkginfo                            1.4.2         
pluggy                             0.7.1         
ply                                3.11          
prometheus-client                  0.3.1         
prompt-toolkit                     1.0.15        
ptyprocess                         0.6.0         
py                                 1.6.0         
pycodestyle                        2.3.1         
pycparser                          2.19          
pyflakes                           1.6.0         
Pygments                           2.2.0         
pylint                             1.9.3         
pyparsing                          2.2.1         
pytest                             3.8.1         
pytest-cov                         2.5.1         
python-coveralls                   2.9.1         
python-dateutil                    2.7.3         
pytz                               2018.5        
pywbem                             0.12.1.dev116 /home/ubuntu/projects/pywbem
PyYAML                             3.13          
pyzmq                              17.1.2        
qtconsole                          4.4.1         
readme-renderer                    22.0          
requests                           2.19.1        
requests-toolbelt                  0.8.0         
scandir                            1.9.0         
Send2Trash                         1.5.0         
setuptools                         40.4.3        
simplegeneric                      0.8.1         
singledispatch                     3.4.0.3       
six                                1.11.0        
smmap2                             2.0.4         
snowballstemmer                    1.2.1         
Sphinx                             1.8.1         
sphinx-git                         10.1.1        
sphinxcontrib-websupport           1.1.0         
terminado                          0.8.1         
testfixtures                       5.4.0         
testpath                           0.4.1         
tornado                            4.5.3         
tqdm                               4.26.0        
traceback2                         1.4.0         
traitlets                          4.3.2         
twine                              1.12.1        
typing                             3.6.6         
unittest2                          1.1.0         
urllib3                            1.23          
wcwidth                            0.1.7         
webencodings                       0.5.1         
wheel                              0.31.1        
widgetsnbextension                 3.4.2         
wrapt                              1.10.11       
yamlordereddictloader              0.4.0

**Comment by andy-maier** [comment] 2018-09-30 09:04
**Discussion point:** Can you reproduce this issue?

**Comment by andy-maier** [comment] 2018-10-10 14:20
Karl said the issue did not reoccur, and we agreed to close this issue as non-reproducable.

**Closed by andy-maier** 2018-10-10 14:20 UTC
Labels: help wanted, priority, resolution: invalid
