### ISSUE TITLE
skip_if_moftab_regenerated() skips all tests when individual tests run

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1933] opened 2019-11-05 15:35 UTC
The function skip_if_moftab_regenerated() causes tests to be skipped sometimes if pytest is used to execute individual test files.

**Comment by andy-maier** [comment] 2019-11-07 05:01
From the definition of `skip_if_moftab_regenerated()`

    Skip the testcase if we run against an installed version of pywbem (as
    indicated by the TEST_INSTALLED environment variable), and the testcase
    would re-generate the MOF parsing table files.

The reason for that is that in the TEST_INSTALLED case, we don't want pywbem to modify the installation, because it could be one that is created from an OS-level package for pywbem.

I verified the logic in this decorator, and if the env var TEST_INSTALLED is not set, this decorator never skips the testcase. If the variable is set, the testcase is skipped if the pywbem version under test would re-generate the MOF parsing table files. The latter is concluded from two things: if the pywbem version under test does not tolerate version mismatches between PLY and the MOF parsing table files, and if there are such version mismatches.

I think this logic is OK from a perspective of what it attempts to achieve. If you see a logic error in the actual behavior then we should fix it, but for that you would need to look at the env var TEST_INSTALLED in your environment.

**Comment by KSchopmeyer** [comment] 2019-11-22 20:16
The error occurs in dev environment when mofparsetab has not been built.  Without this test, the test process forces the rebuild of mofparsetab.  With the skip_if_mof_regenerated() it catches the import exception at the beginning of skip_if_mof_regenerated.

Note, however, that for whatever reason it does not ouput the message part of the pytest.skip so the user is confused.

Did a make install to create mofparsetab, etc. and it works.

**Comment by andy-maier** [comment] 2019-11-24 04:58
My first reaction on your finding that this is caused by the skip "We have no mofparsetab or moflextab to import!" was that this is only possible when TEST_INSTALLED is set.

However, when looking at the logic in skip_if_moftab_regenerated(), it is skipped if the moftab files don't exist, regardless of TEST_INSTALLED being set. That is a bug.

In the local test case, the files should be generated if they don't exist. In the TEST_INSTALLED case, they are supposed to be part of the installation, and their non-existence would indicate an issue with the installation.

**Comment by andy-maier** [comment] 2019-11-24 05:35
Fixed in PR #1961 for master and PR TBD for 0.15.0.

**Closed** 2019-11-26 15:43 UTC
Labels: area: code, resolution: fixed, roll back/forward done, type: bug
