### ISSUE TITLE
read-only permission cannot connect to server

### ISSUE THREAD

**Issue by bank32** [pywbem/pywbem#5] opened 2015-12-04 08:56 UTC
Hi pywbem team,

I've tried to connect to the ESXi from my server.

System Engineer granted my account only for read-only and when I've tried to connect is always return Unauthorized from there

    cim_http.pyc in wbem_request(url, data, creds, headers, debug, x509, verify_callback, ca_certs, no_verification, timeout)
        raise AuthError(response.reason)
    if not local:
        --> raise AuthError(response.reason)
    authChal = response.getheader('WWW-Authenticate', '')
    if 'openwbem' in response.getheader('Server', ''):

AuthError: Unauthorized

(full-access permission account can normally access this system)

please kindly support us.

**Comment by andy-maier** [comment] 2015-12-05 15:03
Hi. I don' t have an esxi environment, but I can try to simulate this. Stay tuned.
Andy

Am 4. Dezember 2015 09:56:19 MEZ, schrieb bank32 <notifications@github.com>:

**Comment by andy-maier** [comment] 2015-12-05 15:10
Hi, 
Can you please detail what you mean with "read-only"? Is this something in exsi, or on the server's operating system?
Andy

Am 4. Dezember 2015 09:56:19 MEZ, schrieb bank32 <notifications@github.com>:

**Comment by bank32** [comment] 2015-12-05 15:14
It's a permission to access ESXi granted by vSphere. 

It has 3 choices
1.no access
2.read-only
3.administrator

**Comment by bank32** [comment] 2015-12-10 08:47
Hi Andy,

I want to let you know more about the information regarding my problem.

I try to call method EnumerateInstances from the read-only user but it turned out that I got the AuthError. However, the admin user can use this method just fine. Moreover, I saw from http://www.wbemsolutions.com/tutorials/CIM/wbem-operations.html that EnumerateInstances method can be used for the Basic Read functional group. 

Thanks,
Bank

**Comment by andy-maier** [comment] 2016-01-20 15:34
Hi Bank,
sorry for the delay.

My only suggestion at this point is to turn on debug and post the results. You turn on debug by:

    cli.debug = True

where `cli` is your WbemConnection object. That keeps the last request and response on the cli object, as:

    cli.last_request
    cli.last_reply
    cli.last_raw_request
    cli.last_raw_reply

See http://pywbem.github.io/pywbem/doc/0.8.0/doc/pywbem.cim_operations.WBEMConnection-class.html#debug for details.

Please post these strings here, to see whether that gets us further ahead.
Andy

**Comment by andy-maier** [comment] 2016-01-27 14:37
I have the strong impression that this is not a problem in the PyWBEM Client. In order to make sure it is not, I was asking for the debug information.

An idea came up when Karl and I discussed the issue: It is possible that it is caused by PAM on the server side. There have been cases in the past where the file system with the PAM logs was full, and this caused PAM to respond "unauthorized" to the WBEM server, which would cause the WBEM server to respond "unauthorized" to the client. So as an additional measure, could you please talk with your ESXi admin to make sure that is ruled out?

The debug information of the PyWBEM Client would still be helpful, IMO.

**Comment by bank32** [comment] 2016-02-01 09:32
thanks a lot for your response Andy, but now we already fixed this problem by we moved to python 3 and changed some code but I can't remember what I changed, sorry about that and thank you so much.

**Comment by andy-maier** [comment] 2016-02-09 07:09
Did you do the port to Python 3 yourself, or did you use https://github.com/deejross/python3-pywbem? Or something else?

**Comment by andy-maier** [comment] 2016-02-13 21:02
Closing as no issue. Please re-open (or open a new issue) if it reoccurs.

**Closed by andy-maier** 2016-02-13 21:02 UTC
Labels: help wanted, investigation needed, release: optional
