### ISSUE TITLE
Add test for mof_compiler script

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#711] opened 2017-06-23 15:07 UTC
Neither the wbemcli or mof_compiler scripts are tested in the unit tests.  We need tests for both.

The test definition for wbemcli is in issue #569 so this issue covers adding unit test for mof_compiler script.

**Comment by andy-maier** [comment] 2017-09-28 08:04
Closing this as a duplicate of issue #428.

**Closed** 2017-09-28 08:05 UTC
Labels: area: test, release: optional, resolution: duplicate, type: enhancement
