### ISSUE TITLE
m2crypto set up for ssl 23

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#214] opened 2016-04-13 13:07 UTC
the m2crypto setup allows you to set protocol.  Currently it is set for m2crypto in cim_http and not TLS1.

Not sure if this is a guess, limit, should be externalized, etc. at this point

**Comment by andy-maier** [comment] 2016-04-20 19:08
I assume you mean "Currently it is set for ssl23 in cim_http and not TLS1"?

On configurability of the client: My view is that the server needs to have the ability to be configured with SSL/TLS options. The client just needs to be flexible enough to deal with all kinds of servers and negotiate the security that is actually used. What we need to make sure for the client, is:

* to drop support for SSL 2 + 3 (Google & Mozilla dropped that)
* to have support for TLS 1.1 and 1.2. (Not sure about TLS 1.0).

**Comment by andy-maier** [comment] 2016-05-10 17:48
**DISCUSSION:** This looks like a duplicate of issues #286 and #295. Suggest to close this issue here.

**Comment by KSchopmeyer** [comment] 2016-05-11 13:57
Close as superseded.

**Closed** 2016-05-11 13:57 UTC
Labels: area: code, discussion needed
